default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 500000
  username: lam
  password:

development:
  <<: *default
  database: unifork

test:
  <<: *default
  database: test_unifork

production:
  <<: *default
  database: production_unifork
